<!DOCTYPE tiles-definitions
    [
        <!ELEMENT component-definitions (definition+)>
        <!ELEMENT tiles-definitions (definition+)>
        <!ELEMENT definition (put*, putList*)>
        <!ATTLIST definition
            name CDATA #REQUIRED
            page CDATA #IMPLIED
            path CDATA #IMPLIED
            extends CDATA #IMPLIED
            role CDATA #IMPLIED
            template CDATA #IMPLIED
            controllerClass CDATA #IMPLIED
            controllerUrl CDATA #IMPLIED>
        <!ELEMENT put (#PCDATA)>
        <!ATTLIST put
            name CDATA #REQUIRED
            value CDATA #IMPLIED
            type (string | page | template | definition) #IMPLIED
            content CDATA #IMPLIED
            direct (true | false) #IMPLIED>
        <!ELEMENT putList ( (add* | item* | bean* | putList*)+) >
        <!ATTLIST putList
            name CDATA #REQUIRED>
        <!ELEMENT putListElements (add | item | bean)>

        <!ELEMENT add (#PCDATA)>
        <!ATTLIST add
            value CDATA #IMPLIED
            type (string | page | template | definition) #IMPLIED
            content CDATA #IMPLIED
            direct (true | false) #IMPLIED>
        <!ELEMENT bean (#PCDATA)>
        <!ATTLIST bean
            classtype CDATA #REQUIRED>
        <!ELEMENT item (#PCDATA)>
        <!ATTLIST item
            value CDATA #REQUIRED
            link CDATA #REQUIRED
            classtype CDATA #IMPLIED
            icon CDATA #IMPLIED
            tooltip CDATA #IMPLIED>
    ]>
<!-- 
/**
 *  tiles.xml
 *
 * (C) Copyright IBM Corp. 2005
 *
 * THIS FILE IS PROVIDED UNDER THE TERMS OF THE COMMON PUBLIC LICENSE
 * ("AGREEMENT"). ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS FILE
 * CONSTITUTES RECIPIENTS ACCEPTANCE OF THE AGREEMENT.
 *
 * You can obtain a current copy of the Common Public License from
 * http://www.opensource.org/licenses/cpl1.0.php
 *
 * Author:     Michael Bauschert
 *
 * Contributors:
 *
 * Definition of tiles-layouts
 *
 */
 -->

<tiles-definitions>
	<definition name="standard-layout" path="/layout.jsp">
		<put name="header" value="header.jsp" />
		<put name="menu" value="menu" />
		<put name="content" value="content" />
	</definition>
	
	<definition name="index.tiles" extends="standard-layout">
		<put name="menu" value="tree.jsp" />
		<put name="content" value="content.jsp" />
	</definition>
	
	<definition name="wizardPage.tiles" extends="standard-layout">
		<put name="menu" value="tree.jsp" />
		<put name="content" value="wizardPage.jsp" />
	</definition>

	<definition name="cimomLogin.tiles" extends="standard-layout">
		<put name="menu" value="tree.jsp" />
		<put name="content" value="cimomLogin.jsp" />
	</definition>

	<definition name="cimomLogout.tiles" extends="standard-layout">
		<put name="menu" value="tree.jsp" />
		<put name="content" value="cimomLogout.jsp" />
	</definition>

	<definition name="editPage.tiles" extends="standard-layout">
		<put name="menu" value="tree.jsp" />
		<put name="content" value="editPage.jsp" />
	</definition>

	<definition name="helpPage.tiles" extends="standard-layout">
		<put name="menu" value="tree.jsp" />
		<put name="content" value="helpPage.jsp" />
	</definition>

</tiles-definitions>